# Generated by Django 6.0.5 on 2026-05-27 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_app.session'),
        ),
    ]
